stages:
  - test
  - package


test:
  stage: test
  script:
    - apt-get update -yqq
    - apt-get install -y cmake git
    - export LD_LIBRARY_PATH=$HOME/.local/lib/:$LD_LIBRARY_PATH
    - git clone --depth=1 https://github.com/lloyd/yajl.git
    - cd yajl && ./configure --prefix=$HOME/.local/
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local/ && make && make install
    - cd ..
    - pip install -r requirements.txt
    - py.test --ignore tests/integration --assert=plain
    - py.test tests/integration --assert=plain


package:
  stage: package
  script: python setup.py sdist
  artifacts:
    paths:
      - dist/
