image: technomaniac/trellio:latest

before_script: pip install -r requirements.txt

stages:
  - test
  - package


test:
  stage: test
  script:
    - py.test --ignore tests/integration --assert=plain
    - py.test tests/integration --assert=plain


package:
  stage: package
  script: python setup.py sdist
  artifacts:
    paths:
      - dist/
