image: technomaniac/trellio:latest

stages:
  - test
  - pypi

test:
  stage: test
  script:
    - pip install -r requirements.txt --upgrade
    - py.test --ignore tests/integration --assert=plain
    - py.test tests/integration --assert=plain

pypi:
  stage: pypi
  script:
    - python setup.py sdist upload
