image: technomaniac/trellio:latest

stages:
  - test
  - package

test:
  stage: test
  script:
    - pip install -r requirements.txt --upgrade
    - py.test --ignore tests/integration --assert=plain
    - py.test tests/integration --assert=plain

package:
  stage: package
  script: python setup.py sdist
  artifacts:
    paths:
      - dist/
